
trigger:
- master

pool:
  name: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
      # PowerShell script to create a sample text file on Azure VM
      New-Item -Path 'C:\Sample' -ItemType Directory
      Set-Content -Path 'C:\Sample\sample.txt' -Value 'This is a sample text file created by Azure 
  displayName: 'Run a one-line script'
